In [2]:
import numpy as np
import pandas as pd

In [3]:
pd.__version__

'2.0.3'

In [8]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data -O housing.csv

'wget' is not recognized as an internal or external command,
operable program or batch file.


In [9]:
df= pd.read_csv(r"D:\Zoomcamp ML\Week 1\raw.githubusercontent.com_alexeygrigorev_datasets_master_housing.csv")

In [12]:
len(df.columns)

10

In [15]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [17]:
df.ocean_proximity.nunique()

5

In [18]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [28]:
df[df['ocean_proximity'] == "NEAR BAY"].describe()

longitude     latitude  housing_median_age   total_rooms  \
count  2290.000000  2290.000000         2290.000000   2290.000000   
mean   -122.260694    37.801057           37.730131   2493.589520   
std       0.147004     0.185434           13.070385   1830.817022   
min    -122.590000    37.350000            2.000000      8.000000   
25%    -122.410000    37.730000           29.000000   1431.250000   
50%    -122.250000    37.790000           39.000000   2083.000000   
75%    -122.140000    37.907500           52.000000   3029.750000   
max    -122.010000    38.340000           52.000000  18634.000000   

       total_bedrooms   population   households  median_income  \
count     2270.000000  2290.000000  2290.000000    2290.000000   
mean       514.182819  1230.317467   488.616157       4.172885   
std        367.887605   885.899035   350.598369       2.017427   
min          1.000000     8.000000     1.000000       0.499900   
25%        289.000000   718.250000   275.000000       2.834750   
50%        423.000000  1033.500000   406.000000       3.818650   
75%        628.750000  1495.000000   599.250000       5.054425   
max       3226.000000  8276.000000  3589.000000      15.000100   

       median_house_value  
count         2290.000000  
mean        259212.311790  
std         122818.537064  
min          22500.000000  
25%         162500.000000  
50%         233800.000000  
75%         345700.000000  
max         500001.000000

In [34]:
df['total_bedrooms'].fillna(df['total_bedrooms'].mean()).describe()

count    20640.000000
mean       537.870553
std        419.266592
min          1.000000
25%        297.000000
50%        438.000000
75%        643.250000
max       6445.000000
Name: total_bedrooms, dtype: float64

In [35]:
df['total_bedrooms'].describe()

count    20433.000000
mean       537.870553
std        421.385070
min          1.000000
25%        296.000000
50%        435.000000
75%        647.000000
max       6445.000000
Name: total_bedrooms, dtype: float64

In [43]:
x = np.array(df[df['ocean_proximity'] == 'ISLAND'][['housing_median_age','total_rooms','total_bedrooms']])

In [46]:
x

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [47]:
XTX = x.T.dot(x)

In [51]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [49]:
np.linalg.inv(XTX)

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [48]:
y = np.array([950, 1300, 800, 1000, 1300])

In [54]:
w = (np.linalg.inv(XTX).dot(x.T)) * y

In [55]:
w

array([[-7.84328036, -8.49171012, -1.85727372, 25.65143741, 15.6641364 ],
       [-1.57559761,  1.44833145,  1.11724729, -1.03214974, -1.43907321],
       [ 7.16646682, -3.92552691, -3.64100058,  1.81685089,  4.28243922]])